apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: python-server
        image: hsri/ping-pong-python:v1
        ports:
        - containerPort: 8080
      - name: go-server
        image: hsri/ping-pong-go:v1
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-service
spec:
  selector:
    app: ping-pong
  ports:
  - name: python-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: go-port
    protocol: TCP
    port: 3001
    targetPort: 3001
  type: LoadBalancer
