apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: go-server
        image: hsri/ping-pong-go
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-service
spec:
  selector:
    app: ping-pong
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
