apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: python-server
        image: hsri/ping-pong-python
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-service
spec:
  selector:
    app: ping-pong
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer

