apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: python-server
        image: hsri/ping-pong-python:v2
        ports:
        - containerPort: 8082
      - name: go-server
        image: hsri/ping-pong-go:v2
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-service
spec:
  selector:
    app: ping-pong
  ports:
  - name: shared-port
    protocol: TCP
    port: 8085
    targetPort: 8085
  type: LoadBalancer
